### ISSUE TITLE
️🛠 - Add UI/UX polish 

### ISSUE THREAD

**Issue by maxwellmattryan** [maxwellmattryan/apellummusic.com#28]
### Task description

The UI looks good statically but the website could "feel" a bit better. This would be things like animations, more hover effects, etc.

### Requirements

- [x] Add "All rights reserved" in website (fix copyright text in general)
- [x] Add better hover effects for music card
- [x] Fix scroll behavior of header
