### ISSUE TITLE
️🛠 - Prepare for "Protocol EP" release

### ISSUE THREAD

**Issue by maxwellmattryan** [maxwellmattryan/apellummusic.com#42]
### Task description

I need to do a few things in order to get this release out of the way.

### Requirements

- [x] Add _So Seductive_ bootleg
    - [x] Find high-quality album art
    - [x] Change hue to purple 
- [ ] Add _Protocol EP_ music item in EPK
- [x] Change copyright year
- [x] Re-order music links in sidebar (Spotify > Apple Music > SoundCloud > Bandcamp)
- [x] Re-write bios and fine tune EPK
    - [x] Update music info in EPK
    - [x] Update in Google Drive
    - [x] Update in Google Cloud
    - [x] Update on website
    - [x] Update on socials:
        - [x] Facebook
        - [x] SoundCloud
        - [x] Mixcloud
        - [x] Spotify
        - [x] Apple Music
        - [x] Resident Advisor
        - [x] Bandcamp 
        - [x] YouTube
