### ISSUE TITLE
️🛠 - Support multiple streaming platform links for music

### ISSUE THREAD

**Issue by maxwellmattryan** [maxwellmattryan/apellummusic.com#44]
### Task description

This task is more specifically related to the EPK music cards - they should support multiple links where applicable.

### Requirements

- [ ] Support Spotify links
- [ ] Support Apple Music links 
- [ ] Support SoundCloud links
- [ ] Support Bandcamp links 
- [ ] Support each platform simultaneously
