### ISSUE TITLE
️🛠 - Add music page

### ISSUE THREAD

**Issue by maxwellmattryan** [maxwellmattryan/apellummusic.com#9]
### Task description

This will be a dedicated page showcasing the music work I've done (producing and DJing). Use [this](https://www.oliver-koletzki.de/) for inspo

### Requirements

- [x] Use common interfaces with EPK music data for new music page
- [ ] Support multiple URLs per music item (default to first one)
- [x] Support hiding of music items
- [x] Add feature flag for music page
